export * as authApi from './auth'
export * as foodpApi from './foodp'
export * as friendApi from './friend'
export * as friendRequestApi from './friendRequest'
export * as userApi from './user'
export * as postApi from './post'